# Generated by Django 2.2.7 on 2019-11-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Uebung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Sporteintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numberOfWarmupSets', models.IntegerField()),
                ('numberOfWorkSets', models.IntegerField()),
                ('commentOfTheDay', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.Kategorie')),
                ('warumupExercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebung_warmup', to='SportApp.Uebung')),
                ('workExercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebung_work', to='SportApp.Uebung')),
            ],
        ),
    ]
