# Generated by Django 2.2.7 on 2019-11-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporteintrag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='numberOfWarmupSets',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='numberOfWorkSets',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='warumupExercise',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='workExercise',
        ),
        migrations.AddField(
            model_name='sporteintrag',
            name='exercises',
            field=models.ManyToManyField(to='SportApp.Uebung'),
        ),
        migrations.AddField(
            model_name='uebung',
            name='numberOfReps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uebung',
            name='numberOfSets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
