# Generated by Django 2.2.7 on 2019-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0002_auto_20191128_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporteintrag',
            name='exercises',
        ),
        migrations.AddField(
            model_name='sporteintrag',
            name='warmExercises',
            field=models.ManyToManyField(related_name='Warmup', to='SportApp.Uebung'),
        ),
        migrations.AddField(
            model_name='sporteintrag',
            name='workExercises',
            field=models.ManyToManyField(related_name='Workout', to='SportApp.Uebung'),
        ),
    ]
