# Generated by Django 2.2.7 on 2019-11-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0004_auto_20191128_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporteintrag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SportApp.Kategorie'),
        ),
        migrations.AlterField(
            model_name='sporteintrag',
            name='commentOfTheDay',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sporteintrag',
            name='numberOfWarmReps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sporteintrag',
            name='numberOfWarmSets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sporteintrag',
            name='numberOfWorkReps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sporteintrag',
            name='numberOfWorkSets',
            field=models.IntegerField(null=True),
        ),
    ]
