# Generated by Django 2.2.7 on 2019-11-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0005_auto_20191128_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporteintrag',
            name='numberOfWarmReps',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='numberOfWarmSets',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='numberOfWorkReps',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='numberOfWorkSets',
        ),
        migrations.CreateModel(
            name='Uebungseintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfSets', models.IntegerField(null=True)),
                ('numberOfReps', models.IntegerField(null=True)),
                ('isWorkout', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.Uebung')),
                ('sportEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.Sporteintrag')),
            ],
        ),
    ]
