# Generated by Django 2.2.7 on 2019-11-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0006_auto_20191128_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporteintrag',
            name='warmExercises',
        ),
        migrations.RemoveField(
            model_name='sporteintrag',
            name='workExercises',
        ),
    ]
