# Generated by Django 2.2.7 on 2019-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0007_auto_20191128_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporteintrag',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
