# Generated by Django 2.2.7 on 2019-11-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0008_auto_20191129_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sporteintrag',
            old_name='date',
            new_name='dateOfEntry',
        ),
    ]
