# Generated by Django 2.2.7 on 2019-12-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0009_auto_20191129_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uebungseintrag',
            name='exercise',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SportApp.Uebung'),
        ),
        migrations.AlterField(
            model_name='uebungseintrag',
            name='numberOfReps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uebungseintrag',
            name='numberOfSets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
