# Generated by Django 2.2.7 on 2019-12-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0010_auto_20191202_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uebungseintrag',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportApp.Uebung'),
        ),
    ]
