version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/web/static
    ports:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static:
